#!/bin/bash
#

# take screenshot
import -window root /tmp/screenshot.png

# blur it
#convert -mosaic /tmp/screenshot.png /tmp/screenshotblur.png
echo $(dirname "$0")/pixelize
$(dirname "$0")/pixelize -s 10 -m 2 /tmp/screenshot.png /tmp/screenshotblur.png
#convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
rm /tmp/screenshot.png

# lock the screen
i3lock -i /tmp/screenshotblur.png

# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0
